// <auto-generated />
using System;
using EmployeeMgtSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeMgtSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250830110857_SeedEmployees")]
    partial class SeedEmployees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeMgtSystem.Models.tbl_Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("tbl_Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 1,
                            Email = "jane.smith@example.com",
                            HireDate = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith",
                            Salary = 40000m
                        },
                        new
                        {
                            Id = 2,
                            Department = 2,
                            Email = "michael.j@example.com",
                            HireDate = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Michael Johnson",
                            Salary = 50000m
                        },
                        new
                        {
                            Id = 3,
                            Department = 3,
                            Email = "emily.davis@example.com",
                            HireDate = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Emily Davis",
                            Salary = 38000m
                        },
                        new
                        {
                            Id = 4,
                            Department = 0,
                            Email = "david.wilson@example.com",
                            HireDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "David Wilson",
                            Salary = 60000m
                        },
                        new
                        {
                            Id = 5,
                            Department = 1,
                            Email = "sophia.brown@example.com",
                            HireDate = new DateTime(2023, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sophia Brown",
                            Salary = 42000m
                        },
                        new
                        {
                            Id = 6,
                            Department = 2,
                            Email = "james.taylor@example.com",
                            HireDate = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "James Taylor",
                            Salary = 55000m
                        },
                        new
                        {
                            Id = 7,
                            Department = 3,
                            Email = "olivia.anderson@example.com",
                            HireDate = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Olivia Anderson",
                            Salary = 47000m
                        },
                        new
                        {
                            Id = 8,
                            Department = 0,
                            Email = "daniel.thomas@example.com",
                            HireDate = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Daniel Thomas",
                            Salary = 52000m
                        },
                        new
                        {
                            Id = 9,
                            Department = 2,
                            Email = "ava.martinez@example.com",
                            HireDate = new DateTime(2023, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ava Martinez",
                            Salary = 48000m
                        },
                        new
                        {
                            Id = 10,
                            Department = 0,
                            Email = "sohel048@gmail.com",
                            HireDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sohel Shaikh",
                            Salary = 45000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
